spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: producer
          uri: lb://producer
          predicates:
            - Path=/producer/**
        - id: consumer
          uri: lb://consumer
          predicates:
            - Path=/consumer/**

  config:
    import: "optional:configserver:http://config-server:8000"

server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
   #   defaultZone: http://service-registry:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

